### PR TITLE
svcplugin and other bugfixes

### LINKED ISSUE #345: Repeated skydns2 errors while using consul cluster store
When Netplugin is using consul cluster store and etcd is not running in the system, netplugin repeatedly prints this error:

time="May  2 21:04:38.854514705" level=error msg="skydns2: failed to register service: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Put http://127.0.0.1:4001/v2/keys/skydns/default/contiv-net/app/0e73eeeac56e: dial tcp 127.0.0.1:4001: getsockopt: connection refused]) [0]" 
time="May  2 21:04:38.854601941" level=error msg="Service refresh failed for appcontiv-net. Error: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Put http://127.0.0.1:4001/v2/keys/skydns/default/contiv-net/app/0e73eeeac56e: dial tcp 127.0.0.1:4001: getsockopt: connection refused]) [0]"

### PR DESCRIPTION
**Pull request by shaleman**
- Fix #345 and #344 seen at a customer. Adds tests for both scenarios.
- Vagrantfile changes to run a cluster in etcd or consul modes so that we can run consul tests without etcd in the system
- Add checks to see Veth interfaces and OVS configuration already exists
- Rearrange svcplugin code to make it work in consul cluster.
-  Move to svcplugin to new etcd client
- Remove the delay in creating default tenant
- Now that CI is stable, re-enables skydns in CI runs
- Adds a system test to verify skydns service discovery works
- Print out all netplugin errors logs at the end of the system-test so that we can debug CI failures

### CODE REVIEW

File: drivers/ovsSwitch.go [hunk 1]
```diff
@@ -265,6 +265,15 @@ func (sw *OvsSwitch) CreatePort(intfName string, cfgEp *mastercfg.CfgEndpointSta
 		ovsIntfType = "internal"
 	}
 
+	// If the port already exists in OVS, remove it first
+	if sw.ovsdbDriver.IsPortNamePresent(ovsPortName) {
+		// Delete it from ovsdb
+		err := sw.ovsdbDriver.DeletePort(ovsPortName)
+		if err != nil {
+			log.Errorf("Error deleting port %s from OVS. Err: %v", ovsPortName, err)
+		}
```
Comment (jojimt) [inline drivers/ovsSwitch.go]: I think a Infof or Debugf would be useful here.

File: drivers/ovsdriver.go [hunk 2]
```diff
@@ -88,10 +88,13 @@ func (d *OvsDriver) getIntfName() (string, error) {
 		// Pick next port number
 		d.oper.CurrPortNum++
 		intfName := fmt.Sprintf("vport%d", d.oper.CurrPortNum)
+		intfName2 := fmt.Sprintf("vvport%d", d.oper.CurrPortNum)
```
Comment (jojimt) [inline drivers/ovsdriver.go]: It seems like we should be returning two interface names from this function?

File: netplugin/netd.go [hunk 3]
```diff
@@ -242,6 +242,33 @@ func processEpState(netPlugin *plugin.NetPlugin, opts cliOpts, epID string) erro
 	return err
 }
 
+//processBgpEvent processes Bgp neighbor add/delete events
+func processBgpEvent(netPlugin *plugin.NetPlugin, opts cliOpts, hostID string,
+	isDelete bool) (err error) {
+
+	if opts.hostLabel != hostID {
+		log.Errorf("Ignoring Bgp Event on this host")
+		return
```
Comment (jojimt) [inline netplugin/netd.go]: We should have either a return value here or make it a void function.

File: netplugin/netd.go [hunk 4]
```diff
@@ -242,6 +242,33 @@ func processEpState(netPlugin *plugin.NetPlugin, opts cliOpts, epID string) erro
...
+	} else {
+		err = netPlugin.AddBgp(hostID)
+		operStr = "create"
+	}
+	if err != nil {
+		log.Errorf("Bgp operation %s failed. Error: %s", operStr, err)
+	} else {
+		log.Infof("Bgp operation %s succeeded", operStr)
+	}
+	return
```
Comment (jojimt) [inline netplugin/netd.go]: Here too. Should have resulted in a compile error...

Comment (erikh) [inline netplugin/netd.go]: https://tour.golang.org/basics/7

Comment (jojimt) [inline netplugin/netd.go]: Interesting. One of the golang "features" I would rather stay away from...

Comment (erikh) [inline netplugin/netd.go]: I agree.

File: drivers/ovsSwitch.go (hunk 1 above)
Comment (shaleman) [inline drivers/ovsSwitch.go]: ok. i'll add a Debugf

File: drivers/ovsdriver.go (hunk 2 above)
Comment (shaleman) [inline drivers/ovsdriver.go]: Since the name of veth pair is passed between different layers of the driver, we pass only one and derive the other one as needed..

File: netplugin/netd.go (hunk 4 above)
Comment (shaleman) [inline netplugin/netd.go]: Btw, this i didn't add this code. I just moved this code from bottom of the file to middle where all the other event handlers are there. I'll be happy to make the return values more explicit.

Comment (jojimt) [inline netplugin/netd.go]: Your call. I just thought it was odd.

File: drivers/ovsdriver.go (hunk 2 above)
Comment (shaleman) [inline drivers/ovsdriver.go]: Actually, let me use getOvsPortName() wrapper to make this clearer..

File: netplugin/netd.go (hunk 4 above)
Comment (shaleman) [inline netplugin/netd.go]: I agree with the comment.. I'm not a fan of named return values either..

Comment (abhinandanpb) [inline netplugin/netd.go]: I will fix it in my next commit.

Comment (shaleman) [inline netplugin/netd.go]: Already fixed.. Missed your opportunity @abhinandanpb  :)
